language: python

python:
  - "3.8"

addons:
  mariadb: 10.3
  

install:
        - sudo apt-get install -y python3-mysqldb
        - pip install -r requirements.txt 
        - pip install -r tests/requirements.txt 

script:
        - cp ispyb_core_config_example.yml ispyb_core_config.yml
        - cp ispyb_ssx_config_example.yml ispyb_ssx_config.yml
        - cp ispyb_em_config_example.yml ispyb_em_config.yml

        - cd scripts
        - bash create_core_db.sh
        - bash create_ssx_db.sh
        - bash run_all.sh
        - cd ..
        - pylint -E pyispyb.app pyispyb.core pyispyb.ssx
        - coverage run -m pytest tests/core
        - bash <(curl -s https://codecov.io/bash)
        - coverage run -m pytest tests/ssx
        - bash <(curl -s https://codecov.io/bash)
